branches:
  only: 
    - master
language: python
python:
  - "2.7"
  - "3.7"
  - "nightly" # points to the latest development branch e.g. 3.7-dev
# command to install dependencies
allow_failures:
  - python: nightly # Allow all tests to fail for nightly
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
# command to run tests
script: nosetests -s
